version: 0.0
os: linux
files:
  - source: /server
    destination: /home/ubuntu/lab-aws/server
hooks:
  BeforeInstall:
    - location: /home/ubuntu/lab-aws/server/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/ubuntu/lab-aws/server/scripts/after_install.sh
      timeout: 300
      runas: root
