version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/lab-aws/app
hooks:
  BeforeInstall:
    - location: server/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: server/scripts/after_install.sh
      timeout: 300
      runas: root
