version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Install Dependencies...
      - cd server
      - npm install
  build:
    commands:
      - echo Building App...
      - cd server
      - npm run build
    finally:
      - echo Building Packages Completed  `date`...
